---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/sonarr-config:/config
      - ./data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/radarr-config:/config
      - ./data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/bazarr-config:/config
      - ./data/media:/media
    ports:
      - "6767:6767"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/jellyfin-config:/config
      - ./data/media:/data
    ports:
      - "8096:8096"
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

    restart: unless-stopped

  jellyseerr:
    image: docker.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=13012
      - PGID=13000
      - UMASK=002
      - TZ=Asia/Kuwait
    volumes:
      - ./config/jellyseerr-config:/app/config
    ports:
      - '5056:5055'
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent-config:/config
      - ./data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=30033
      - PGID=30033
      - TZ=Asia/Kuwait
    volumes:
      - ./config/sabnzbd-config:/config
      - ./data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped

